### ISSUE TITLE
pip3 install broken

### ISSUE THREAD

**Issue by seanxlliu** [tducret/amazon-scraper-python#34]
When I used latest version of pip to install, I encountered the following error. Pip changed its internal implementation recently, which is probably why this broke

pip3 --version

pip 21.2.4 from /.../lib/python3.9/site-packages/pip (python 3.9)

pip3 install -U amazonscraper

```
Collecting amazonscraper
  Downloading amazonscraper-0.1.2.tar.gz (8.6 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/liuxiaolu/Work/amazon/analyzer/env/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_f415d4529b4844dcb21f497a53af1347/setup.py'"'"'; __file__='"'"'/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_f415d4529b4844dcb21f497a53af1347/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-pip-egg-info-t8errgvi
         cwd: /private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_f415d4529b4844dcb21f497a53af1347/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_f415d4529b4844dcb21f497a53af1347/setup.py", line 22, in <module>
        requirements = [str(ir.req) for ir in install_reqs]
      File "/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_f415d4529b4844dcb21f497a53af1347/setup.py", line 22, in <listcomp>
        requirements = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/c0/15/bab4563fe795fadce45ac42eea0ed0988d7f478dc9c4ba8d845f0c2d2d4a/amazonscraper-0.1.2.tar.gz#sha256=b683d98fabe0f0548a28707bf399a1e32840fdd4f6117fba8152c6bbd4dc6bc5 (from https://pypi.org/simple/amazonscraper/) (requires-python:>=3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading amazonscraper-0.1.1.tar.gz (8.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/liuxiaolu/Work/amazon/analyzer/env/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_2dd4acea14d8428e8993c5ab3b4911e3/setup.py'"'"'; __file__='"'"'/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_2dd4acea14d8428e8993c5ab3b4911e3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-pip-egg-info-kj603xnr
         cwd: /private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_2dd4acea14d8428e8993c5ab3b4911e3/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_2dd4acea14d8428e8993c5ab3b4911e3/setup.py", line 22, in <module>
        requirements = [str(ir.req) for ir in install_reqs]
      File "/private/var/folders/_1/9b6tfd017bx3878sxkcsyhk40000gn/T/pip-install-8a51jct1/amazonscraper_2dd4acea14d8428e8993c5ab3b4911e3/setup.py", line 22, in <listcomp>
        requirements = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/71/5f/16139dbe286630c2aeda864c3974da01cf016731f50d3f4108dda5102831/amazonscraper-0.1.1.tar.gz#sha256=1254df358f7329d3d8e6c5d66a44b362d7cd3c699e1e5dd2848a76b4f05c4d39 (from https://pypi.org/simple/amazonscraper/) (requires-python:>=3). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by seanxlliu** [comment]
I saw this may be fixed in the latest setup.py. So just wait for the new release

**Comment by lalainarahajason** [comment]
Hi, this issue is resolved ? i got same problem

**Comment by utkuarslandev** [comment]
Same here
```
Collecting amazonscraper
  Using cached amazonscraper-0.1.2.tar.gz (8.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
